### ISSUE TITLE
Unable to download SSL Issue

### ISSUE THREAD

**Issue by gaz2k1** [LowPowerLab/ATX-Raspi#2]
Hi,

This package will not download, faced with the following error:

pi@retropie:~ $ sudo wget https://raw.githubusercontent.com/LowPowerLab/ATX-Raspi/master/shutdownchecksetup.sh
--2016-09-02 20:36:18--  https://raw.githubusercontent.com/LowPowerLab/ATX-Raspi/master/shutdownchecksetup.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 62.252.172.241
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|62.252.172.241|:443... connected.
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [0]: Close notify
Unable to establish SSL connection.

**Comment by LowPowerLab** [comment]
Try it in a browser, it works.
