### ISSUE TITLE
'print "\n' issues

### ISSUE THREAD

**Issue by awilliam** [LowPowerLab/ATX-Raspi#3]
The lines like:

print"\n========...

Are getting installed in the resulting script as:

print "
=====...

Which is invalid syntax.

Installed with sh ./shutdownchecksetup.sh

Where sh is dash 0.5.7-4

**Comment by LowPowerLab** [comment]
My guess it's probably dash on debian that's doing this.
Works OK with bash, as per instructions.

**Comment by LowPowerLab** [comment]
BTW the script is marked as `#!/bin/bash` and should be run with bash.
