### ISSUE TITLE
Autostart of shutdowncheck does not work

### ISSUE THREAD

**Issue by elodur** [LowPowerLab/ATX-Raspi#5]
I use atxraspi with the volumio distro, which does not use rc.local any more, but systemd. As far as I can see your script is using rc.local to start. Is there a possibility to edit it to using systemd? I'm afraid I don't know how to do it myself.

**Comment by LowPowerLab** [comment]
Not an issue, please post in the forum. Some discussions there mention volumio, so please search before you post.
Thanks

**Comment by elodur** [comment]
I did search your forum and did not find a solution. I just thought it was an issue because your install script uses rc.local for starting, which is not used in Volumio any more. (I thought some other, bigger distros switched to systemd as well). In the end I got it working with systemd, thanks a lot.
________________________________
